GET http://localhost:3000/api/v1/user/redivreto@gmail.com

###

GET http://localhost:3000/api/v1/user/

###

POST http://localhost:3000/login

###

GET http://localhost:3000/api/v1/user/
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVkbW9uZEB1bml0bi5pdCIsImlhdCI6MTY1MzY3MjQ1M30.KM89kDcP8fNcae23jlkIfy69yAQ2f5-5SVnBhcbWs5c

###

POST http://localhost:3000/api/v1/user/redivreto@gmail.com/score
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVkbW9uZEB1bml0bi5pdCIsImlhdCI6MTY1MzY3MjQ1M30.KM89kDcP8fNcae23jlkIfy69yAQ2f5-5SVnBhcbWs5c